### PR TITLE
add contains assert

### PR DESCRIPTION
**Pull request by brunoqueiros**
A new assert to check if a string contains certain string.

t.contains(value, expected, [message]);

### CODE REVIEW

**Comment by sindresorhus** [comment]
Hmm, not sure about this. Now that we have [`power-assert` support](https://github.com/sindresorhus/ava#enhanced-asserts) it doesn't really make sense to add a bunch more assertion methods as you can just use `t.true()`. In this case it would be `t.true(foo.includes('bar'));`, although `[].includes` is [currently not working](https://github.com/sindresorhus/ava/issues/263), but will be fixed.

**Comment by brunoqueiros** [comment]
I think that is easier to have more assertions because the test file will be cleaner and more easy to maintaining. I think there should have both, that way the user can choose what use.

**Comment by sindresorhus** [comment]
```js
t.contains(foo, 'bar');
// vs
t.ok(foo.includes('bar'));
```

// @twada @uiureo

**Comment by shinnn** [comment]
Contrary to the PR author's opinion, `t.contains` won't simplify the test file, I think.

There are a lot of JavaScript objects that have `indexOf` method (array, string, Node's buffer, ...), but this `t.contains` function doesn't check its argument type. So whenever we use `t.contains` we should also check the object type.

**Comment by brunoqueiros** [comment]
It's not even necessary, your arguments are right. I'll close the PR.

**Comment by twada** [comment]
I agree with @sindresorhus and @shinnn.

I've developed [power-assert](https://github.com/power-assert-js/power-assert) to prevent tests from bloating assertion methods. Less is more.

I know it's a bit opinionated. But AVA is opinionated too ;)

**Pull request closed without merging**
