### PR TITLE
use tap test runner instead of tape.

### PR DESCRIPTION
**Pull request by jamestalmage**

### CODE REVIEW

**Comment by vdemedes** [comment]
Instead of:

```js
var tap = require('tap');
var test = tap.test;
```

you can just:

```js
var test = require('tap').test;
```

**Comment by jamestalmage** [comment]
done.
Why does `tap` set the timeout per file? That is crazy. Why not per individual test?

I understand why you guys were arguing for 30 seconds now.

**Comment by jamestalmage** [comment]
Let's do "per test" timeouts in AVA.

**Comment by vdemedes** [comment]
`$ tap -t 0 test/*.js` should solve the timeout issue.

**Comment by jamestalmage** [comment]
I did 150 seconds.

**Comment by vdemedes** [comment]
`tap -t150` is not a good way to specify a value. It should be `tap -t 150`.

**Comment by sindresorhus** [comment]
I'm fine with 150s. That way it doesn't hang the CI forever if we have some kind of timeout issue.

**Comment by vdemedes** [comment]
Yeah, global timeout should be there, was just pointing out a better way to set an argument value.

**Comment by sindresorhus** [comment]
I prefer to full flag with `=` too, for readability: `tap --timeout=150`.

**Comment by vdemedes** [comment]
Sure, that works too!

**Comment by jamestalmage** [comment]
done

**Comment by vdemedes** [comment]
Thanks!

**Pull request merged**
