### PR TITLE
document nyc's source map support

### PR DESCRIPTION
**Pull request by novemberborn**
As promised in <https://github.com/sindresorhus/ava/issues/185#issuecomment-161093243>.

### CODE REVIEW

**Comment by novemberborn** [comment]
`nyc@5.0.0` is out so I've updated the copy to reflect.

**Comment by vdemedes** [comment]
LGTM

**Comment by sindresorhus** [comment]
LGTM

**Comment by vdemedes** [comment]
@novemberborn Thank you!

**Comment by novemberborn** [comment]
@vdemedes no problem! :smile:

**Pull request merged**
