### PR TITLE
Test on Node.js v4.x and v5.x

### PR DESCRIPTION
**Pull request by ntwb**

### CODE REVIEW

**Comment by vdemedes** [comment]
`nvm install stable` installs latest stable Node.js version:

screen shot 2015-12-29 at 3 53 34 pm

**Comment by ntwb** [comment]
The latest stable is NodeJS v5.3.0 https://nodejs.org/en/

Travis needs to update their docs, but here on the [NVM #Usage](https://github.com/creationix/nvm#usage) section of the docs its documented about the `stable` alias being deprecated.

In https://github.com/creationix/nvm/issues/870 there is a discussion about future aliases such as `LTS`, and other options...

**Comment by ntwb** [comment]
Using `4` and `5` per the pull request will use NVM to always test the latest 4.x.x (currently 4.2.4) and 5.x.x (currently 5.3.0) version/branches respectively so until NodeJS v6 is out things should be right here for a while :smirk: 

Also see https://github.com/sindresorhus/grunt-sass/pull/263 and @sindresorhus :+1: for these changes

**Comment by vdemedes** [comment]
Node.js stable releases are even numbers, so `5.3.0` is not a stable release.

I just talked to @sindresorhus and we agreed to test for `4.x` too as it is LTS release. I'll accept all your PRs now, thanks ;)

**Comment by sindresorhus** [comment]
> Node.js stable releases are even numbers, so 5.3.0 is not a stable release.

Not exactly true. All major versions are stable, it's just the even ones are LTS releases. https://nodejs.org/en/blog/community/node-v5/

**Comment by vdemedes** [comment]
@sindresorhus correcting myself, Node.js stable releases are even minor numbers.

**Comment by vdemedes** [comment]
Oh ok, I should update myself on release cycles.

**Comment by ntwb** [comment]
Yep, clear as mud all of this isn't it :smirk: 

I started down the road of updating WordPress' NPM dependencies and basically sending pull requests everywhere so that firstly the current stable versions of NodeJS are at least being tested in Travis CI, once thata done I can then look at updating any tests and/or dependencies :)

**Comment by ntwb** [comment]
Thanks for merging, and all that jazz :+1:

**Comment by vdemedes** [comment]
@ntwb Thank **you**!

**Pull request merged**
