### PR TITLE
use faucet tap reporter

### PR DESCRIPTION
**Pull request by jamestalmage**
Until this is resolved: https://github.com/scottcorgan/tap-spec/issues/40

### CODE REVIEW

**Comment by vdemedes** [comment]
The output on Travis is a bit crappy - https://travis-ci.org/sindresorhus/ava/jobs/91561792. Although faucet is really cool.

**Comment by jamestalmage** [comment]
Yeah, we can switch back when `tap-spec` gets fixed. I have a PR in for it's dependency, so hopefully he follows through and pulls that upstream.

I would prefer to continue working on AVA for now and just go with this. If he doesn't merge and pull the fix upstream in a few days, I will patch `tap-spec` myself and we can use that.

**Comment by vdemedes** [comment]
Regarding this tap-spec issue #231, is there a way I can reproduce this? I wrote a failing test and tap-spec exited correctly with `1` exit code.

**Comment by jamestalmage** [comment]
You need to throw an uncaught error a `tape` test (so the `tape` command exits suddenly).

A failing test that does not cause the process to exit will still fail the build.

**Comment by jamestalmage** [comment]
See this build: https://travis-ci.org/sindresorhus/ava/jobs/91510425

Exits passing after only 45 tests.

**Comment by vdemedes** [comment]
Damn, still can't reproduce. My test file:

```js
var test = require('tap').test;

test(function (t) {
	t.end();
});

test(function (t) {
	var obj = {};
	obj.child.value = 1;
});

test(function (t) {
	t.end();
});

```

**Comment by vdemedes** [comment]
Ok, got it, I was using `tap` instead of `tape`. Maybe we should just use `tap` in AVA tests? I can't find the difference between those too.

// @sindresorhus

**Comment by sindresorhus** [comment]
@vdemedes I'm fine with switching to `tap`. It's more actively developed and generally better.

`tape` tl;dr, `tape` was initially made to add browser support to `tap`. `tap` also had a long period of inactivity, but after npm decided to beef up their test suite it has gotten a lot of <3.

**Comment by vdemedes** [comment]
Great, so let's just use `tap` and `tap-spec` reporter.

**Comment by jamestalmage** [comment]
closed in favor of #234

**Pull request closed without merging**
