### PR TITLE
WIP: add test suite for es2015 polyfills

### PR DESCRIPTION
**Pull request by jamestalmage**
Based on the conversation in #263, I'm starting to work up a test suite that 
actually excercises ALL the ES2015 features, so we know what we are missing.

This is a rough start. If someone wants to help divide and conquer, just ping me on 
Gitter to discuss.

### CODE REVIEW

**Comment by vdemedes** [comment]
Oooh, I am not sure about this one. Our test suite will grow tremendously, if we test every ES6 feature. That's definitely up to babel project to test these. We just need to fix our babel issues and get it right.

**Comment by sindresorhus** [comment]
Good idea! But I think this would be better as a separate project. Something like a ES2015 tester project that both we and Babel could consume.

**Comment by sindresorhus** [comment]
There's also https://github.com/kangax/compat-table which already does this. Should probably just reuse that one instead.

**Comment by vdemedes** [comment]
@sindresorhus +1

**Comment by thejameskyle** [comment]
@sindresorhus https://github.com/kangax/compat-table is a bad test suite for ES6 features, it's very shallow. https://github.com/tc39/test262 is better

**Comment by sindresorhus** [comment]
I think we should put this on hold until we have upgraded to Babel 6.

**Comment by sindresorhus** [comment]
> But I think this would be better as a separate project. Something like a ES2015 tester project that both we and Babel could consume.

Closing for the above reason. @jamestalmage If you're no longer interested in doing this and think it's still relevant, can you open an issue?

**Pull request closed without merging**
