### PR TITLE
Fix command format in readme

### PR DESCRIPTION
**Pull request by alexbooker**

### CODE REVIEW

**Comment by sindresorhus** [comment]
The current command is correct. `npm test` swallows flags, so we use the `--` to indicate it should ignore the following flags.

**Comment by alexbooker** [comment]
Hm. I still don't really understand why the `--` is needed. 

Would it make sense to elaborate under the ["Running tests with watch mode enabled" section](https://github.com/sindresorhus/ava/blob/master/docs/recipes/watch-mode.md#running-tests-with-watch-mode-enabled)?

**Comment by sindresorhus** [comment]
http://unix.stackexchange.com/questions/11376/what-does-double-dash-mean-also-known-as-bare-double-dash

**Comment by BarryThePenguin** [comment]
@alexbooker the npm docs elaborate on passing arguments to [npm run-script](https://docs.npmjs.com/cli/run-script)

**Comment by alexbooker** [comment]
Thanks, both.

**Pull request closed without merging**
