### PR TITLE
Use `tap.match` in unit tests

### PR DESCRIPTION
**Pull request by sotojuan**
This helps out with https://github.com/sindresorhus/ava/issues/256 by converting the regex `t.true()` tests into `t.match()`.

Let me know if I missed any!

### CODE REVIEW

**Comment by sindresorhus** [comment]
LGTM

**Comment by vdemedes** [comment]
LGTM

**Comment by vdemedes** [comment]
@sotojuan Could you please squash 2 commits into one?

**Comment by sotojuan** [comment]
The commit message is a little weird, but I got it (had never squashed commits so I figured I'd play it safe).

**Comment by vdemedes** [comment]
@sotojuan What's wrong with the commit message? It is totally fine.

**Comment by vdemedes** [comment]
Thank you @sotojuan, keep those PRs coming!

**Comment by sotojuan** [comment]
Oh I guess it's fine then (just thought it was curious that the message for the CLI one was in the long description part). Thanks and I will!

**Pull request merged**
