### PR TITLE
Removed redundant line from assertion error output in mini reporter

### LINKED ISSUE #422: Clean up redundant assertion error output.
Currently the following:

```js
test(t => t.ok(false))
```

Will log the following:

```
false == true
AssertionError: false == true
  ... remaining stack-trace ...
```

This is redundant.

It only happens for enhanced assertions.

I think the solution could be as simple as: `err.message + stripFirstLine(err.stack)`.

### PR DESCRIPTION
**Pull request by naptowncode**
Fixes #422. Removed the `AssertionError: ...` line of output.

### CODE REVIEW

**Comment by vdemedes** [comment]
Errors are not always instances of `AssertionError`, so we definitely should not just remove the first line of `err.stack`.

**Comment by naptowncode** [comment]
Ah, I see. Should I leave out the `error.message` instead? The message will always be in the first line of the stack trace anyway.

**Comment by sindresorhus** [comment]
> Errors are not always instances of AssertionError, so we definitely should not just remove the first line of err.stack.

@vdemedes But the message is always the first line of the stack no matter what kind of error.

**Comment by sindresorhus** [comment]
@naptowncode This looks good to me. Can you fix the merge conflict?

**Comment by naptowncode** [comment]
@sindresorhus Done, though AppVeyor seems to not like it.

**Comment by sotojuan** [comment]
AppVeyor is very rude sometimes :cry:

**Comment by sindresorhus** [comment]
Thank you @naptowncode :)

**Pull request merged**
