### PR TITLE
Add Code of Conduct

### PR DESCRIPTION
**Pull request by sindresorhus**
Adapted from http://contributor-covenant.org/

This is important to have.

### CODE REVIEW

**Comment by sindresorhus** [comment]
@forresst @AlbertoFuente You can find ready made translations here: http://contributor-covenant.org/version/1/3/0/es/code_of_conduct.md http://contributor-covenant.org/version/1/3/0/fr/code_of_conduct.md Just replace `[INSERER ADRESSE EMAIL]` with `sindresorhus@gmail.com`.

**Comment by kevva** [comment]
:+1: I believe everyone agrees with this.

**Comment by vdemedes** [comment]
LGTM!

**Comment by sindresorhus** [comment]
Yup, I just wanted everyone to be aware.

**Comment by AlbertoFuente** [comment]
:+1: Totally agree

**Comment by ariporad** [comment]
:+1:

**Comment by forresst** [comment]
:+1: 
@sindresorhus Done for french translation  sindresorhus/ava-docs@5ed5937218c193a6920ccd2bbb786f4327f189b2

**Pull request merged**
