### PR TITLE
Cache node_modules on appveyor and disable npm progress bar

### PR DESCRIPTION
**Pull request by ariporad**
Since @fscherwi beat me to Travis, this just caches `node_modules` on AppVeyor. It should speed up the build quite a bit.

### CODE REVIEW

**Comment by ariporad** [comment]
I also disabled the spinner and progress bar on npm to make the output look a lot nicer. I can enable the http logging so you can still see what's going on, if you like.

**Comment by jamestalmage** [comment]
Same as my comment in #361, I think caching `node_modules` is a bad idea. It is a lot more tempting for AppVeyor since it is so slow, but probably still not worth the risks.

I'm confused by the second commit. If I review the AppVeyor output from your PR, and others like it, they seem identical. What am I missing?

**Comment by ariporad** [comment]
@jamestalmage: Huh, AppVeyor must have changed it. Never mind.

Although, I think we should cache node_modules on AppVeyor, because npm on AV is a lot slower, and any dependency mess ups will be caught by travis.

**Comment by jamestalmage** [comment]
> I think we should cache node_modules on AppVeyor, because npm on AV is a lot slower, and any dependency mess ups will be caught by travis.

That is a tempting thought. However, it [doesn't seem the build is actually any faster](https://ci.appveyor.com/project/sindresorhus/ava/history) between your first and second commit, should it be?

**Comment by ariporad** [comment]
@jamestalmage: No. It should be faster between this branch and master.

**Comment by jamestalmage** [comment]
For your first commit there wouldn't have been a cache yet, so it should have been slow. Check the [build history](https://ci.appveyor.com/project/sindresorhus/ava/history), discounting hung builds - this PR takes about the same amount of time to build.

**Comment by ariporad** [comment]
Hmm... I guess never mind then. (Although that's awful strange).

**Comment by jamestalmage** [comment]
> Although that's awful strange

I don't know. If I had to guess, I would bet AppVeyor proxies the `npm` repository, so installs happen very fast.

**Comment by ariporad** [comment]
Yeah, Probably.

**Comment by sindresorhus** [comment]
The slowest part about AppVeyor is that your builds are always queued for a long time before starting. AppVeyor probably deprioritize free plans.

**Pull request closed without merging**
