### PR TITLE
Add pinkie test

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Why? I don't it's our responsibility to test whether pinkie works or not.

**Comment by TrySound** [comment]
@sindresorhus Sorry, forget about description 
https://github.com/floatdrop/pinkie/pull/12#issuecomment-157350268

**Comment by jamestalmage** [comment]
@sindresorhus - I asked for this. Not sure where the source of his problem is (be it pinkie or something in AVA-- but probably pinkie)

@TrySound Does this fail on local windows boxes, or just AppVeyor?

**Comment by TrySound** [comment]
@jamestalmage I tried local. But I can't install node 0.10 on 64-bit with nvm. On node 0.12 test passes. Trying here

**Comment by jamestalmage** [comment]
You can't just install the 32 bit version? 

`nvm install 0.10.40 32`?

I've got a copy of 32 bit windows, so I am not sure

**Comment by TrySound** [comment]
@jamestalmage Oh, it just didn't let use short version `0.10` with weird notice

**Comment by jamestalmage** [comment]
the version of nvm on windows is weird...

everything about windows ....

**Comment by TrySound** [comment]
@jamestalmage Still passes. Okay, will try to remove chucks of cosmiconfig

**Comment by TrySound** [comment]
@jamestalmage Something wrong with test files order in log :))

**Comment by jamestalmage** [comment]
@TrySound 
So no problem in AVA or pinkie?

**Comment by TrySound** [comment]
@jamestalmage Maybe in appveyor?

**Comment by jamestalmage** [comment]
Opening private gitter chat so we can stop spamming everybody.

**Pull request closed without merging**
