### PR TITLE
Update ava version in readme package.json

### PR DESCRIPTION
**Pull request by zachlysobey**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Nah, if I accept this we'll have to bump it for every version. We'll bump it to 1.0.0 when we get there. Thanks though.

**Comment by jamestalmage** [comment]
We could write an `npm version` script to handle swapping this out every time you publish with `np`.

**Comment by sindresorhus** [comment]
@jamestalmage I think that's overdoing it. I don't see the point. It will be moot anyways when we do 1.0.0. And it's just an example. Not meant to be copy-pasted.

**Comment by jamestalmage** [comment]
:+1:

**Pull request closed without merging**
