### PR TITLE
Doc: Generate gh-pages base on MD files with Docpress

### PR DESCRIPTION
**Pull request by zckrs**
Hi,

With [Docpress](https://github.com/docpress/docpress) we can have a github pages  who based content on `docs` folder.

Temporarily you can view result here http://zckrs.github.io/ava/ pushed by [Travis build](https://travis-ci.org/zckrs/ava/jobs/106703077#L1634).

If you are interested and ready to merge I will configure for the source repo and squash commit.

**Note**:
* media moved into docs folder

### CODE REVIEW

**Comment by sindresorhus** [comment]
Looks good, but not sure of its use-case when it's just a rendering of the readme.

**Comment by zckrs** [comment]
Commits squashed

* 10ad1a2 Move media into docs/media
* 076aa09 Use "docpress"
* 3f96378 Auto build/deploy by TravisCI

***

Documentations accessible via a web application with a navigation can help some users.
And AVA can be more popular with it.

**Comment by zckrs** [comment]
For deployement by TravisCI you should add env variable `GITHUB_TOKEN` in https://travis-ci.org/sindresorhus/ava/settings

**Comment by sindresorhus** [comment]
> Documentations accessible via a web application with a navigation can help some users.

We already have a `Table of Contents` menu in the readme.

> And AVA can be more popular with it.

Not really a concern right now.

-

None of the arguments are very convincing.

@vdemedes @jamestalmage What do you think about adding this?

**Comment by jamestalmage** [comment]
I think it looks nice. I like the Nav. I like that we get it almost for free just by generating a Readme.

@zckrs - You made a number of edits (moving things in to doc folder, etc). That I don't understand why they were necessary. I'm assuming that's required by Docpress? That would be my one big objection. I don't want to spend time trying to make my Readme acceptable to some third party post-processor.

My gut is that it's got potential, but maybe a bit premature to start focusing on this / letting it take up the maintainers time.

**Comment by zckrs** [comment]
@jamestalmage yes I moved media folder into docs because Docpress is based on `docs` to resolve path.

**Comment by vdemedes** [comment]
I agree with @sindresorhus point, it's a pretty wrapper for the exactly same content. I don't see how it would help AVA become more popular.

Moreover, we have a website planned when we reach near-1.0 release (#162).

@zckrs We have to pass on this PR for now, but thank you for your work and effort to contribute to AVA! Little tip, to avoid these kinds of situations, where work does not get merged, I recommend opening an issue first and see what other people think about your idea.

**Comment by zckrs** [comment]
No problem
You are right I should open issue but I like coding ^^

**Pull request closed without merging**
