### PR TITLE
use is-equal instead of deeper for es6 set and map support

### PR DESCRIPTION
**Pull request by mayankchd**

### CODE REVIEW

**Comment by mayankchd** [comment]
Failing on Node.js 0.10 as it doesn't support Set and Map

**Comment by jamestalmage** [comment]
For Node 0.10, lookup how Set and Map are referenced when transformed by AVA, should be something like:

```
var Map = require('babel-runtime/lib/fn/Map');
// or 
var Map = require('core-js/lib/fn/Map');
```

**Comment by sindresorhus** [comment]
I would prefer to just add support for Map/Set in `deeper`. `is-equal` brings in 3 MB of dependencies.

**Comment by sindresorhus** [comment]
Closing in favor of https://github.com/othiym23/node-deeper/issues/2.

**Comment by jamestalmage** [comment]
:+1: I agree. `2.3MB` is just way to big. AVA already takes just this side of eternity to download. @twada and others have put in major effort slimming down their packages and our download size. This would be a major step in the wrong direction. 

Sorry @mayankchd. Otherwise your PR looked great. It's not your fault that package is so bloated.

**Comment by mayankchd** [comment]
Thanks! I like ava a lot!

**Pull request closed without merging**
