### PR TITLE
Add a benchmark suite

### PR DESCRIPTION
**Pull request by jamestalmage**
Comments welcome:

Collect benchmark data for a branch:

```
$ node bench/run
```

Once you have collected data from two / three branches:

```
$ node bench/compare
```

Pretty Tables!

screenshot 2016-01-31 02 06 05

### CODE REVIEW

**Comment by jamestalmage** [comment]
You can now launch a subset of the suite:

```
node bench/run.js concurrent/sync.js serial/sync.js -- concurrent/sync.js -- serial/sync.js
```

Note the `--` separator. The above would be the same as benchmarking all three of the following commands.

```
ava concurrent/sync.js serial/sync.js
ava concurrent/sync.js
ava serial/sync.js
```

Also if you are benchmarking a suite that should fail, you must add the `--should-fail` flag in that group

```
node bench/run.js concurrent/sync.js -- --should-fail other/failures.js
```

The above benchmarks two commands, but expects the second one to fail.

**Comment by jamestalmage** [comment]
I think this gets us a good start.

@sindresorhus @vdemedes - Any other benchmark suites that should be added?

**Comment by sindresorhus** [comment]
Looks superb! Such pretty tables :)

I think it would be useful with a quick script to automate gathering data from master and the last commit and then run the tests. This would be the most common operation, so would be good to automate it, but we can do that later.

**Comment by sindresorhus** [comment]
unicorn14

**Pull request closed without merging**
