### PR TITLE
Include actual and expected when the number of assertions doesn't match the plan.

### LINKED ISSUE #102: When assertion count is incorrect, output the expected and actual values.
I see that the actual count is recorded, but I'm not sure how to see it when running `ava`.

https://github.com/sindresorhus/ava/blob/master/lib/test.js#L150-L158

```
❯ npm test

> npm-check@4.1.2 test /Users/dgreene/projects/npm-check
> xo && ava ./test


  ✖ require Assertion count does not match planned

  1 test failed

  1. require
  Error
    at Test.plan (/Users/dgreene/projects/npm-check/node_modules/ava/lib/test.js:87:19)
    at Test.<anonymous> (/Users/dgreene/projects/npm-check/test/test.js:10:7)
    at step (/Users/dgreene/projects/npm-check/test/test.js:5:273)
    at Test.fn (/Users/dgreene/projects/npm-check/test/test.js:5:99)
```

The above is using using `master` with `power-assert` added.

Similar output using the published version

```
> npm-check@4.1.2 test /Users/dgreene/projects/npm-check
> xo && ava ./test


  ✖ require Assertion count does not match planned

  1 test failed

  1. require
  Error
    at Test.plan (/Users/dgreene/projects/npm-check/node_modules/ava/lib/test.js:59:19)
    at Object.callee$0$0$ (/Users/dgreene/projects/npm-check/test/test.js:10:7)
    at Test.callee$0$0 [as fn] (/Users/dgreene/projects/npm-check/test/test.js:32:26)
```

### PR DESCRIPTION
**Pull request by ariporad**
This isn't as good as it could be, as it doesn't have a nice assertion diff, because that's generated by power assert, which does all kinds of other things too that we don't want

Fixes #102.

@sindresorhus, @jamestalmage, @vdemedes: thoughs?

### CODE REVIEW

**Comment by sindresorhus** [comment]
It's an ok workaround, but I don't think this is the correct way to solve it for real. We already supply the `actual` and `expected` to the assert error and it should handle the output, but somehow that's lost. Might be because we overwrite the `.stack`.

**Comment by sindresorhus** [comment]
Could be more succinct. Something like, but better:

> Assertion count of 4 does not match planned of 5

**Comment by ariporad** [comment]
@sindresorhus: It's not related to the stack. Check my comment in #102. It's a power-assert thing.

**Comment by ariporad** [comment]
@sindresorhus: Message fixed.

**Comment by jamestalmage** [comment]
Just wondering here. Now that #371 is merged, should we just use that for this? Is a stack trace really going to be that helpful? Especially since `test.exit()` is now always deferred via a promise?

**Comment by sindresorhus** [comment]
@jamestalmage I would still want to know which assertion and test that triggers the "incorrect plan count error".

**Comment by jamestalmage** [comment]
We would be setting it via `test._setAssertError`, so we will still know which test triggered that.
We currently only check the assert count when the test exits, not for every assert, so you can't know which assertion caused the error now.

(`test._setAssertError` is a bit of a misnomer now).

**Comment by ariporad** [comment]
@sindresourhus, @jamestalmage: yeah, I think we probably should. I'll work on that in the am.

**Comment by jamestalmage** [comment]
@ariporad - How close are you to finishing this?

**Comment by ariporad** [comment]
@jamestalmage, @sindresorhus: OK, rebased onto master, and now uses `AvaError`.

**Comment by sindresorhus** [comment]
Tests are failing.

**Comment by ariporad** [comment]
@sindresorhus: of course they are.

**Comment by ariporad** [comment]
Naturally, They're all false negatives.

@sindresorhus: Do AvaError's need `.operator`s, `.actual`s or `.expected`s?

**Comment by ariporad** [comment]
@jamestalmage: ^^^^^^^^^^

**Comment by sindresorhus** [comment]
@ariporad Sorry, missed this one. Can you rebase on master and fix the merge conflict?

> Do AvaError's need .operators, .actuals or .expecteds?

No

**Comment by sindresorhus** [comment]
So, what should we do about this PR?

**Comment by sindresorhus** [comment]
Would like to see this land, but closing for now to clean up inactive PRs. @ariporad Feel free to do a new one if you ever have time ;)

**Pull request closed without merging**
