### PR TITLE
[WIP] - Refactor Runner

### PR DESCRIPTION
**Pull request by jamestalmage**
WIP refactoring `runner.js`. One goal is to support addressable test indexes which could be used implement #421. 

The `test-collection` class makes all the test data serializable, so it can be passed to the parent thread yet (I'm not actually doing that yet).

Still really early. Just wanted some feedback.

### CODE REVIEW

**Comment by sindresorhus** [comment]
> One goal is to support addressable test indexes which could be used implement #421.

Is there any benefit to this other than for #421? #421 should really not have any impact on how we structure the code. It's just an early discussion that could easily be abandoned.

**Comment by jamestalmage** [comment]
I think it's going to end up cleaner / easier to understand - with better separation of concerns. Also has implications for using domains for logging / error tracking. This is real early stuff. Not ready for serious review. Just wanted you aware of what I was doing

**Comment by sindresorhus** [comment]
Alright

**Comment by jamestalmage** [comment]
closing in favor of #466

**Pull request closed without merging**
