### PR TITLE
use the test file path in the Babel `only` prop instead of a pattern

### PR DESCRIPTION
**Pull request by sindresorhus**
since we're only using this once per file now

http://babeljs.io/docs/usage/options/#options

### CODE REVIEW

**Comment by sindresorhus** [comment]
@vdemedes Any thoughts on how to best test to ensure that this is working correctly? Meaning it only transpiles the tested files and nothing more.

**Comment by vdemedes** [comment]
Well, if we are executing babel per file, we should just set file name to `only` property.
`whitelist` property is not for files, it is a list of transform to include.

**Comment by vdemedes** [comment]
@sindresorhus Does passing a string to `only`, instead of a pattern, works?

**Comment by sindresorhus** [comment]
By whitelist I meant `only`.

**Comment by sindresorhus** [comment]
> Does passing a string to only, instead of a pattern, works?

It should in theory as the prop is being arrayified, but we need a test for the behavior anyways.

**Comment by ahdinosaur** [comment]
what about for projects that are using `babel` to transpile the rest of their app (e.g. by running their code with `babel-node`), wouldn't this force babel to only transpile the test files?

**Comment by sindresorhus** [comment]
> what about for projects that are using babel to transpile the rest of their app (e.g. by running their code with babel-node), wouldn't this force babel to only transpile the test files?

We already limit that in master. This PR only changes it to only ignore the path explicitly instead of using a ignore pattern. You would just do whatever you with your existing test framework that doesn't support ES2015 builtin, not sure what that is?

**Pull request merged**
