### PR TITLE
Document watch mode

### LINKED ISSUE #532: Document --watch
> I'm thinking we add it undocumented, dogfood it, and only document it when we feel it's stable enough and we're ready to take on the addition support burden.

https://github.com/sindresorhus/ava/issues/70#issuecomment-173746486

* [ ] Document the `--watch` and `--source` CLI flags
* [ ] Add to README
* [ ] Mention `DEBUG=ava:watcher`

### PR DESCRIPTION
**Pull request by novemberborn**
Document watch mode. Fixes #532.

Contains a squashed #597, so just check the last commit. Will rebase once #597 has landed.

### CODE REVIEW

**Comment by novemberborn** [comment]
Pushed a fixup which:

* changes `sports` to `comes with`
* links to `ignore-by-default`'s `index.js` for the ignored directories
* uses `<kbd>` to mark up the `rs` input, reworded the sentence as well
* updated example source patterns

Still to do:

* [ ] add `-S` as shorthand for `--source`
* [ ] support `r + Enter` to rerun all tests, in addition to `rs + Enter`
* [ ] resolve whether source negation patterns should disable all default ignored directories, whether those default directories can be overriden, etc (this may need to be a follow-up issue)

**Comment by sindresorhus** [comment]
>  support r + Enter to rerun all tests, in addition to rs + Enter

I meant just `r`. No Enter. What really is the point of having to press Enter?

> resolve whether source negation patterns should disable all default ignored directories, whether those default directories can be overriden, etc (this may need to be a follow-up issue)

Yeah, let's not dilute this PR with that. Can you open a new issue?

**Comment by novemberborn** [comment]
> I meant just r. No Enter. What really is the point of having to press Enter?

This may be a bit tricky. It requires enabling raw mode on `stdin` which then seems to intercept ^C etc. It also seemed to affect my shell after killing AVA. Happy to open a ticket though as a future improvement?

I've added `r + Enter` now. I'm inclined to keep `rs + Enter` for those users with nodemon muscle memory (or who may use AVA and nodemon in the same project). Can remove if others disagree.

> Yeah, let's not dilute this PR with that. Can you open a new issue?

#614

---

This has now been rebased against master. `-S` shorthand has been added.

**Comment by sindresorhus** [comment]
> Happy to open a ticket though as a future improvement?

:+1:

> I'm inclined to keep rs + Enter for those users with nodemon muscle memory (or who may use AVA and nodemon in the same project).

Sure, that's fine, but `r+enter` should be the documented one.

**Comment by novemberborn** [comment]
> Sure, that's fine, but r+enter should be the documented one.

Right now they're both documented, with `r + Enter` being first.

**Comment by sindresorhus** [comment]
> Right now they're both documented, with r + Enter being first.

I don't see the point of documenting both. Your argument is that you have `rs` + Enter as muscle memory. I don't see why we would document `rs` to new users without that muscle memory and create overhead for them by making them have to choose which one to pick.

**Comment by novemberborn** [comment]
Ticket: #615

**Comment by novemberborn** [comment]
> I don't see the point of documenting both. Your argument is that you have rs + Enter as muscle memory. I don't see why we would document rs to new users without that muscle memory and create overhead for them by making them have to choose which one to pick.

How would users realize `rs` also works? Other than accidentally. Maybe that's good enough though?

**Comment by sindresorhus** [comment]
> How would users realize rs also works? Other than accidentally. Maybe that's good enough though?

Isn't that the point? If they have to read the docs, they can just as easily use the shorter `r`+Enter version.

**Comment by novemberborn** [comment]
You'd have to read the docs to even find out about r+enter though.

**Comment by sindresorhus** [comment]
> You'd have to read the docs to even find out about r+enter though.

Exactly. Unless it's muscle memory, users have to read the docs anyways, so there's really no reason to document both behaviors, when `r` is shorter. I consider `rs` a graceful handling of a mistyping, not something we'd want to officially support. IMHO, we should only have [one way to do something](https://www.python.org/dev/peps/pep-0020/).

**Comment by novemberborn** [comment]
OK will edit in the morning. Good to go otherwise?

**Comment by sindresorhus** [comment]
:+1:

**Comment by novemberborn** [comment]
Updated. Anything else?

**Comment by sindresorhus** [comment]
Looks good :)

**Pull request merged**
