### PR TITLE
Fix issue with CLI throwing on Windows - fixes #164

### LINKED ISSUE #164: Invalid regular expression error when running from the CLI on Windows
```
D:\_host\github\postcss-inline-svg>ava

D:\_station\nvm\v0.12.7\node_modules\ava\cli.js:70
                .replace(new RegExp(path.sep, 'g'), separator);
                         ^
SyntaxError: Invalid regular expression: /\/: \ at end of pattern
    at new RegExp (native)
    at prefixTitle (D:\_station\nvm\v0.12.7\node_modules\ava\cli.js:70:12)
    at ChildProcess.test (D:\_station\nvm\v0.12.7\node_modules\ava\cli.js:89:12)
    at ChildProcess.emit (events.js:107:17)
    at ChildProcess.<anonymous> (D:\_station\nvm\v0.12.7\node_modules\ava\lib\fork.js:47:6)
    at ChildProcess.emit (events.js:110:17)
    at handleMessage (child_process.js:324:10)
    at Pipe.channel.onread (child_process.js:352:11)
```

Structure
```
test:
- svg/*.svg
- apply-data.js
- ast2data.js
- index.js
```

### PR DESCRIPTION
**Pull request by TrySound**
This works perfectly. regexpless solution :)

### CODE REVIEW

**Comment by vdemedes** [comment]
Tests are failing, could you take a look?

**Comment by sindresorhus** [comment]
Ignore the Appveyor failure, it was already failing.

**Comment by sindresorhus** [comment]
@TrySound I've commented this before, but please try harder with your titles ;)

**Comment by sindresorhus** [comment]
Thanks for the fix :)

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/ava/releases/tag/v0.4.2

**Pull request closed without merging**
