### PR TITLE
Add skipped test count to builtin reporters

### PR DESCRIPTION
**Pull request by sotojuan**
This fixes https://github.com/sindresorhus/ava/issues/408 by adding the skipped test count to the builtin reporters, in yellow color.

Let me know if I missed anything or if another color is more appropriate.

### CODE REVIEW

**Comment by kevva** [comment]
Nice work @sotojuan. lgtm :+1:

**Comment by sindresorhus** [comment]
LGTM :)

**Comment by jamestalmage** [comment]
LGTM: 

screenshot 2016-01-08 19 35 39

screenshot 2016-01-08 19 35 04

**Comment by vdemedes** [comment]
If mini reporter uses yellow for skipped number, we should do the same for the verbose reporter as well (it's cyan there).

**Comment by jamestalmage** [comment]
@vdemedes - see #412

**Pull request closed without merging**
