### PR TITLE
improve context sharing for beforeEach/afterEach

### PR DESCRIPTION
**Pull request by sindresorhus**
re https://github.com/sindresorhus/ava/pull/106#issuecomment-150966370

### CODE REVIEW

**Comment by sindresorhus** [comment]
// @vdemedes @schnittstabil

**Comment by vdemedes** [comment]
I think it's good to go!

**Comment by schnittstabil** [comment]
There is an unnecessary(?) `this.context = {}` within the `Test` constructor in lib/test.js remaining.

**Comment by sindresorhus** [comment]
@schnittstabil I didn't put it there, but I assume it's so that even tests without hooks can have a context, for consistency. @vdemedes Correct?

**Comment by vdemedes** [comment]
@sindresorhus Yep, correct!

**Pull request merged**
